# Generated by Django 3.2 on 2022-10-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=15, verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido')),
                ('lugar_nacimiento', models.CharField(max_length=50, verbose_name='LugarN')),
                ('fecha_nacimiento', models.DateField(verbose_name='FechaN')),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('canton', models.CharField(max_length=50, verbose_name='Canton')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/A', 'Ninguno')], max_length=20, verbose_name='Sexo')),
                ('tipo_sangre', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('7', 'O+'), ('8', 'O-')], max_length=5, verbose_name='TipoS')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='NombreE')),
                ('parentesco_contacto_emergencia', models.CharField(blank=True, max_length=80, null=True, verbose_name='ParentescoE')),
                ('telefono_contacto_emergencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='CelularE')),
                ('is_menor', models.BooleanField(default=False, verbose_name='Es_menor')),
                ('nombre_tutor', models.CharField(blank=True, max_length=200, null=True, verbose_name='NombreT')),
                ('parentesco_tutor', models.CharField(blank=True, max_length=80, null=True, verbose_name='ParentescoT')),
                ('telefono_tutor', models.CharField(blank=True, max_length=15, null=True, verbose_name='CelularT')),
                ('direccion_tutor', models.CharField(blank=True, max_length=300, null=True, verbose_name='DireccionT')),
            ],
        ),
    ]
